// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRUlNqs8ARGfx0ragVDmd8VVMNa0ly7nY',
    appId: '1:122988240473:web:2327ae2860b82e1c851b48',
    messagingSenderId: '122988240473',
    projectId: 'mobile-apps-go-fish',
    authDomain: 'mobile-apps-go-fish.firebaseapp.com',
    storageBucket: 'mobile-apps-go-fish.appspot.com',
    measurementId: 'G-SSDJ0FM5KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANI0A8qMuxD1Bn35hGZhddOOYq7COiUZo',
    appId: '1:122988240473:android:4ae97e83d3335261851b48',
    messagingSenderId: '122988240473',
    projectId: 'mobile-apps-go-fish',
    storageBucket: 'mobile-apps-go-fish.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmnEtAwVCvpz5hO9zjUhF2CPbpvSOcXGo',
    appId: '1:122988240473:ios:aca01a8428afb253851b48',
    messagingSenderId: '122988240473',
    projectId: 'mobile-apps-go-fish',
    storageBucket: 'mobile-apps-go-fish.appspot.com',
    iosClientId: '122988240473-ls68em2gdut71idbivd05ledt9q73c0a.apps.googleusercontent.com',
    iosBundleId: 'com.colinmcbride.goFishGame',
  );
}
